For my sanity I commented out all earlier tests. Not sure exactly what needs to be refactored inside them, received errors /Users/sarahandyshak/Desktop/French-Bakery.Solution/Bakery.Tests/ModelTests/PastryTests.cs(19,30): error CS1729: 'PastryTests' does not contain a constructor that takes 1 arguments [/Users/sarahandyshak/Desktop/French-Bakery.Solution/Bakery.Tests/BakeryTests.csproj] /Users/sarahandyshak/Desktop/French-Bakery.Solution/Bakery.Tests/ModelTests/PastryTests.cs(38,30): error CS1729: 'PastryTests' does not contain a constructor that takes 1 arguments [/Users/sarahandyshak/Desktop/French-Bakery.Solution/Bakery.Tests/BakeryTests.csproj]